version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: employee-postgres
    environment:
      POSTGRES_DB: employee
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
